services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/code/entrypoint.sh"]
    env_file:
      - ./src/.env
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
    volumes:
      - ./src:/code/src
      - ./src/.env:/code/.env

  db:
    image: postgres:13
    env_file:
      - ./src/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '7666:5432'
    expose:
      - '5432'

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    env_file:
      - ./src/.env
    depends_on:
      - db
    attach: false

  start_up:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./src/.env
    depends_on:
      - db
      - web
    command: python -m scripts.start_up
    volumes:
      - ./src:/code/src
    environment:
      PYTHONPATH: /code/src

  pytest:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./src/.env
    depends_on:
      - db
    command: python -m pytest /code/tests -p no:warnings
    volumes:
      - .:/code
    environment:
      PYTHONPATH: /code/src:/code


volumes:
  postgres-data:
  pgadmin-data:
