"""Strategy table unique constraint

Revision ID: ab52a4cd0508
Revises: 30b7e104752d
Create Date: 2024-11-21 17:15:10.587142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab52a4cd0508'
down_revision: Union[str, None] = '30b7e104752d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_strategies_names_user_ids', 'strategies', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_strategies_names_user_ids', 'strategies', type_='unique')
    # ### end Alembic commands ###
