"""user_id autoincrement

Revision ID: 5d7ba62b48ea
Revises: e736ae2b39bd
Create Date: 2024-11-23 12:48:53.461579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d7ba62b48ea'
down_revision: Union[str, None] = 'e736ae2b39bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
	table_name='users', 
	column_name='id', 
	existing_type=sa.Integer(),
	nullable=False,
	autoincrement=True
	)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
	table_name='users', 
	column_name='id', 
	existing_type=sa.Integer(),
	nullable=False,
	autoincrement=False,
)
    # ### end Alembic commands ###
